blank_issues_enabled: false
contact_links: 
  - name: USB issues (screens, usb, sound cards, arduino disconnects)
    url: https://github.com/SHWotever/SimHub/wiki/USB-Issues-Troubleshooting
  - name: Performances/Lags issues
    url: https://github.com/SHWotever/SimHub/wiki/DashStudio-performance
    about: Anything related to dash studio perforances
  - name: Licence issues
    url: https://www.simhubdash.com/simhub-contact/
    about: Anything related to licence (lost, not received ...)
